### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Nate-Wilkins** [Flet/eslint-to-esformatter#3]
Provide context to rule transform functions.

``` js
module.exports = {
  transform: function (active, arg, options) {
    if (active < 1) return;

    this.log.warn('Not supported in esformatter');
  }
}
```

Whether this be through the function context or with some other logging module like [winston](https://github.com/winstonjs/winston)

**Comment by Flet** [comment]
I don't think console.logging makes sense. This module should just quietly output JSON. `winston` feels more geared towards a full application versus a small module like this.

Perhaps a way to turn on debug logging will suffice? something like https://github.com/visionmedia/debug

Another option would be to make the output JSON more articulate by outputting info/warning data as well as esformatter JSON as part of the same object. The added complexity to the output may not be worth it.

Thoughts?

**Comment by Nate-Wilkins** [comment]
I don't think anybody using this would need that information so I think `require('debug')` will do nicely.

**Comment by Flet** [comment]
:+1:

**Comment by Nate-Wilkins** [comment]
Added let me know if you want changes to the logging :+1:
