### ISSUE TITLE
Deprecated ESLint Rules

### ISSUE THREAD

**Issue by Nate-Wilkins** [Flet/eslint-to-esformatter#4]
Rules that are deprecated by eslint should still have transforms but we need to denote them in someway. 

What I did previously was prefix deprecated rules with a `-` and log a deprecation warning when that rule was in use. 

I'll be adding the deprecated rules later today.

**Comment by Flet** [comment]
What is the purpose of making deprecated rules denoted in the filesystem?

Perhaps export a flag?
`module.exports.deprecated = true;`
(similar to `informative`)

**Comment by Nate-Wilkins** [comment]
That sounds a lot better! When we add those rules we'll use the flag.
